name: wechat_flutter
description: A new Flutter project..

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+101

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter: #flutter sdk
    sdk: flutter
  flutter_localizations: #本地化
    sdk: flutter
  cupertino_icons: 1.0.8 #IOS风格材料图标
  tencent_cloud_chat_sdk: 8.3.6498 #腾讯云im
  archive: ^3.6.1 #腾讯云im生成token需要
  shared_preferences: 2.3.3 #持久化存储
  provider: 6.1.2 #状态管理
  get: 4.6.6 #状态管理
  cached_network_image: 3.4.1 #图片缓存，图片显示
  oktoast: 3.4.0 #toast提示框
  webview_flutter: 4.10.0 #web显示
  image_picker: 0.8.6 #选取图库
  extended_text: 14.2.0 #文本扩展显示
  extended_text_field: 16.0.1 #文字表情混入
  extended_text_library: 12.0.1 #extended 支持库
  url_launcher: 6.3.1 #打开系统浏览器
  connectivity_plus: 6.1.0 #网络连接
  photo_view: 0.15.0 #图片显示
  dio: 5.7.0 #网络请求
  open_file: 3.5.10 #打开文件
  package_info_plus: 8.1.1 #获取包信息
  flutter_sound: 9.17.5 #音频处理
  permission_handler: 11.3.1 #权限处理
  audioplayers: 6.1.0 #音频处理
  video_player: 2.9.2 #视频播放
  lpinyin: 2.0.3 #拼音
  azlistview_plus: 3.0.0 #特殊列表滑动
  wechat_assets_picker: 9.4.1 #微信图库
  photo_manager: 3.5.0 #wechat_assets_picker的配件
  extended_image: 9.0.7 #扩展图片
  platform: 3.1.0 #平台

dependency_overrides:
  js: 0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/bsc.webp
    - assets/images/bar_close.png
    - assets/images/tabbar_contacts_c.webp
    - assets/images/tabbar_contacts_s.webp
    - assets/images/tabbar_discover_c.webp
    - assets/images/tabbar_discover_s.webp
    - assets/images/tabbar_chat_c.webp
    - assets/images/tabbar_chat_s.webp
    - assets/images/tabbar_me_c.webp
    - assets/images/tabbar_me_s.webp
    - assets/images/def_avatar.png
    - assets/images/search_black.webp
    - assets/images/search_white.png
    - assets/images/Contact_Female.webp
    - assets/images/Contact_Male.webp
    - assets/images/right_more.png
    - assets/images/favorite.webp
    - assets/images/contacts_add_newmessage.png
    - assets/images/add_addressicon.png
    - assets/images/ic_delete.webp
    - assets/images/ic_right_arrow_black.webp
    - assets/images/ic_right_arrow_grey.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_no_data.webp

    - assets/images/login/select_avatar.webp
    - assets/images/login/ic_select_have.webp
    - assets/images/login/ic_select_have_grey.webp
    - assets/images/login/ic_select_no.png

    - assets/images/chat/ic_Emotion.webp
    - assets/images/chat/ic_Keyboard.webp
    - assets/images/chat/ic_details_add.png
    - assets/images/chat/ic_voice.webp
    - assets/images/chat/ic_chat_more.webp
    - assets/images/chat/ic_chat_voice.webp
    - assets/images/chat/ic_details_camera.webp
    - assets/images/chat/ic_details_card.webp
    - assets/images/chat/ic_details_favorite.webp
    - assets/images/chat/ic_details_file.webp
    - assets/images/chat/ic_details_localtion.webp
    - assets/images/chat/ic_details_media.webp
    - assets/images/chat/ic_details_photo.webp
    - assets/images/chat/ic_details_red.webp
    - assets/images/chat/ic_details_transfer.webp
    - assets/images/chat/ic_details_video.webp
    - assets/images/chat/voice_volume_1.webp
    - assets/images/chat/voice_volume_2.webp
    - assets/images/chat/voice_volume_3.webp
    - assets/images/chat/voice_volume_4.webp
    - assets/images/chat/voice_volume_5.webp
    - assets/images/chat/voice_volume_6.webp
    - assets/images/chat/voice_volume_7.webp
    - assets/images/chat/sound_left_0.webp
    - assets/images/chat/sound_left_1.webp
    - assets/images/chat/sound_left_2.webp
    - assets/images/chat/sound_left_3.webp
    - assets/images/chat/sound_right_0.png
    - assets/images/chat/sound_right_1.webp
    - assets/images/chat/sound_right_2.webp
    - assets/images/chat/sound_right_3.png
    - assets/images/chat/icon_sight_close.png
    - assets/images/chat/flip_camera_icon_nor.webp

    - assets/images/mine/ic_small_code.png
    - assets/images/mine/ic_wallet.webp
    - assets/images/mine/ic_card_package.png
    - assets/images/mine/ic_emoji.png
    - assets/images/mine/ic_pay.png
    - assets/images/mine/ic_setting.png

    - assets/images/contact/ic_contacts_details.png
    - assets/images/contact/ic_no_public.webp
    - assets/images/contact/ic_tag.webp
    - assets/images/contact/ic_group.webp
    - assets/images/contact/ic_new_friend.webp
    - assets/images/contact/ic_video.png
    - assets/images/contact/ic_voice.png
    - assets/images/contact/ic_offical.webp
    - assets/images/contact/ic_reda.webp
    - assets/images/contact/ic_scanqr.webp
    - assets/images/contact/ic_search_wework.webp
    - assets/images/contact/ic_contact_add.webp

    - assets/images/discover/ff_Icon_album.webp
    - assets/images/discover/ff_Icon_shake.webp
    - assets/images/discover/ff_Icon_bottle.webp
    - assets/images/discover/ff_Icon_browse.webp
    - assets/images/discover/ff_Icon_nearby.webp
    - assets/images/discover/ff_Icon_qr_code.webp
    - assets/images/discover/ff_Icon_search.webp
    - assets/images/discover/game_center_h5.webp
    - assets/images/discover/mini_program.webp
    - assets/images/emoji/
    - assets/images/group/
    - assets/images/wechat/
    - assets/images/wechat/in/

    - assets/data/contacts.json
    - assets/data/friends.json
